[paths]
wer_queue = "C:\\ProgramData\\Microsoft\\Windows\\WER\\ReportQueue"
livekernel_reports = "C:\\Windows\\LiveKernelReports"
minidump = "C:\\Windows\\Minidump"

[wer]
patterns = ["Kernel_193_*", "Kernel_15e_*", "Kernel_1a8_*"]

[livekernel]
folders = ["WATCHDOG", "NDIS", "USBXHCI", "USBHUB3", "PoW32kWatchdog"]

[custom.arc_raiders]
files = [
  "C:\\Games\\ARC Raiders\\Saved\\Logs\\CrashReportClient.ini"
]
dirs = [
  "C:\\Games\\ARC Raiders\\Saved\\Crashes",
  "C:\\Games\\ARC Raiders\\Saved\\CrashReportClient",
  "C:\\Games\\ARC Raiders\\Saved\\WindowsClient",
  "C:\\Games\\ARC Raiders\\Saved\\Config"
]
globs = [
  "C:\\Games\\ARC Raiders\\Saved\\Crashes\\**\\*.dmp",
  "C:\\Users\\Neophile\\AppData\\Local\\Temp\\**\\*.dmp",
  "C:\\Users\\Neophile\\AppData\\Local\\PioneerGame\\Saved\\Crashes\\**\\*.*"
]
